// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package serviceresuest.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the ServiceResuest module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCt_ServiceRequest_CompleteBuilder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACt_ServiceRequest_Complete");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static void aCt_ServiceRequest_Complete(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		aCt_ServiceRequest_CompleteBuilder(
				_serviceRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ServiceRequest_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACT_ServiceRequest_Create");
		return builder;
	}

	public static void aCT_ServiceRequest_Create(IContext context)
	{
		aCT_ServiceRequest_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ServiceRequest_SaveBuilder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACT_ServiceRequest_Save");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static void aCT_ServiceRequest_Save(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		aCT_ServiceRequest_SaveBuilder(
				_serviceRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ServiceRequest_Step1Builder(
		useraccount.proxies.Customer _customer,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACT_ServiceRequest_Step1");
		builder = builder.withParam("Customer", _customer);
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static void aCT_ServiceRequest_Step1(
		IContext context,
		useraccount.proxies.Customer _customer,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		aCT_ServiceRequest_Step1Builder(
				_customer,
				_serviceRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ServiceRequest_Step2Builder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACT_ServiceRequest_Step2");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static void aCT_ServiceRequest_Step2(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		aCT_ServiceRequest_Step2Builder(
				_serviceRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ServiceRequest_ViewBuilder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.ACT_ServiceRequest_View");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static void aCT_ServiceRequest_View(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		aCT_ServiceRequest_ViewBuilder(
				_serviceRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Account_Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.DS_Account_");
		return builder;
	}

	public static java.util.List<administration.proxies.Account> dS_Account_(IContext context)
	{
		Object result = dS_Account_Builder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> administration.proxies.Account.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Document_CreateBuilder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.DS_Document_Create");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static serviceresuest.proxies.Document dS_Document_Create(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		Object result = dS_Document_CreateBuilder(
				_serviceRequest
			)
			.execute(context);
		return result == null ? null : serviceresuest.proxies.Document.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_NewRequestBuilder(
		useraccount.proxies.Customer _customer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.SUB_NewRequest");
		builder = builder.withParam("Customer", _customer);
		return builder;
	}

	public static void sUB_NewRequest(
		IContext context,
		useraccount.proxies.Customer _customer
	)
	{
		sUB_NewRequestBuilder(
				_customer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_ServiceRequest_Step1Builder(
		useraccount.proxies.Customer _customer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.VAL_ServiceRequest_Step1");
		builder = builder.withParam("Customer", _customer);
		return builder;
	}

	public static boolean vAL_ServiceRequest_Step1(
		IContext context,
		useraccount.proxies.Customer _customer
	)
	{
		Object result = vAL_ServiceRequest_Step1Builder(
				_customer
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_ServiceRequest_Step2Builder(
		serviceresuest.proxies.ServiceRequest _serviceRequest,
		serviceresuest.proxies.Equipment _equipment
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.VAL_ServiceRequest_Step2");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		builder = builder.withParam("Equipment", _equipment);
		return builder;
	}

	public static boolean vAL_ServiceRequest_Step2(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest,
		serviceresuest.proxies.Equipment _equipment
	)
	{
		Object result = vAL_ServiceRequest_Step2Builder(
				_serviceRequest,
				_equipment
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_ServiceRequest_ViewBuilder(
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("ServiceResuest.VAL_ServiceRequest_View");
		builder = builder.withParam("ServiceRequest", _serviceRequest);
		return builder;
	}

	public static boolean vAL_ServiceRequest_View(
		IContext context,
		serviceresuest.proxies.ServiceRequest _serviceRequest
	)
	{
		Object result = vAL_ServiceRequest_ViewBuilder(
				_serviceRequest
			)
			.execute(context);
		return (boolean) result;
	}
}
