// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package useraccount.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the UserAccount module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Registration_NewEditBuilder(
		useraccount.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserAccount.ACT_Registration_NewEdit");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static void aCT_Registration_NewEdit(
		IContext context,
		useraccount.proxies.Registration _registration
	)
	{
		aCT_Registration_NewEditBuilder(
				_registration
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Registration_SignupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserAccount.ACT_Registration_Signup");
		return builder;
	}

	public static void aCT_Registration_Signup(IContext context)
	{
		aCT_Registration_SignupBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder get_CustomerAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserAccount.Get_CustomerAccount");
		return builder;
	}

	public static useraccount.proxies.Customer get_CustomerAccount(IContext context)
	{
		Object result = get_CustomerAccountBuilder().execute(context);
		return result == null ? null : useraccount.proxies.Customer.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_PasswordBuilder(
		useraccount.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserAccount.VAL_Password");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static boolean vAL_Password(
		IContext context,
		useraccount.proxies.Registration _registration
	)
	{
		Object result = vAL_PasswordBuilder(
				_registration
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_Registration_NewEditBuilder(
		useraccount.proxies.Registration _registration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("UserAccount.VAL_Registration_NewEdit");
		builder = builder.withParam("Registration", _registration);
		return builder;
	}

	public static boolean vAL_Registration_NewEdit(
		IContext context,
		useraccount.proxies.Registration _registration
	)
	{
		Object result = vAL_Registration_NewEditBuilder(
				_registration
			)
			.execute(context);
		return (boolean) result;
	}
}
