// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package serviceresuest.proxies;

public class Equipment implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceResuest.Equipment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentID("EquipmentID"),
		SerialNo("SerialNo"),
		AssetTag("AssetTag"),
		ModelNo("ModelNo"),
		EquipmentType("EquipmentType"),
		ManufactureDate("ManufactureDate"),
		PurchaseDate("PurchaseDate"),
		WarrantyStatus("WarrantyStatus"),
		ServiceRequest_Equipment("ServiceResuest.ServiceRequest_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentMendixObject)
	{
		if (equipmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentMendixObject = equipmentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static serviceresuest.proxies.Equipment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new serviceresuest.proxies.Equipment(context, mendixObject);
	}

	public static serviceresuest.proxies.Equipment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return serviceresuest.proxies.Equipment.initialize(context, mendixObject);
	}

	public static java.util.List<serviceresuest.proxies.Equipment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> serviceresuest.proxies.Equipment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentID
	 */
	public final java.lang.Long getEquipmentID()
	{
		return getEquipmentID(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentID
	 */
	public final java.lang.Long getEquipmentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.EquipmentID.toString());
	}

	/**
	 * Set value of EquipmentID
	 * @param equipmentid
	 */
	public final void setEquipmentID(java.lang.Long equipmentid)
	{
		setEquipmentID(getContext(), equipmentid);
	}

	/**
	 * Set value of EquipmentID
	 * @param context
	 * @param equipmentid
	 */
	public final void setEquipmentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long equipmentid)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentID.toString(), equipmentid);
	}

	/**
	 * @return value of SerialNo
	 */
	public final java.lang.String getSerialNo()
	{
		return getSerialNo(getContext());
	}

	/**
	 * @param context
	 * @return value of SerialNo
	 */
	public final java.lang.String getSerialNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SerialNo.toString());
	}

	/**
	 * Set value of SerialNo
	 * @param serialno
	 */
	public final void setSerialNo(java.lang.String serialno)
	{
		setSerialNo(getContext(), serialno);
	}

	/**
	 * Set value of SerialNo
	 * @param context
	 * @param serialno
	 */
	public final void setSerialNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serialno)
	{
		getMendixObject().setValue(context, MemberNames.SerialNo.toString(), serialno);
	}

	/**
	 * @return value of AssetTag
	 */
	public final java.lang.String getAssetTag()
	{
		return getAssetTag(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetTag
	 */
	public final java.lang.String getAssetTag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssetTag.toString());
	}

	/**
	 * Set value of AssetTag
	 * @param assettag
	 */
	public final void setAssetTag(java.lang.String assettag)
	{
		setAssetTag(getContext(), assettag);
	}

	/**
	 * Set value of AssetTag
	 * @param context
	 * @param assettag
	 */
	public final void setAssetTag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assettag)
	{
		getMendixObject().setValue(context, MemberNames.AssetTag.toString(), assettag);
	}

	/**
	 * @return value of ModelNo
	 */
	public final java.lang.String getModelNo()
	{
		return getModelNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelNo
	 */
	public final java.lang.String getModelNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelNo.toString());
	}

	/**
	 * Set value of ModelNo
	 * @param modelno
	 */
	public final void setModelNo(java.lang.String modelno)
	{
		setModelNo(getContext(), modelno);
	}

	/**
	 * Set value of ModelNo
	 * @param context
	 * @param modelno
	 */
	public final void setModelNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelno)
	{
		getMendixObject().setValue(context, MemberNames.ModelNo.toString(), modelno);
	}

	/**
	 * Get value of EquipmentType
	 * @param equipmenttype
	 */
	public final serviceresuest.proxies.Enum_EquipmentType getEquipmentType()
	{
		return getEquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType
	 */
	public final serviceresuest.proxies.Enum_EquipmentType getEquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EquipmentType.toString());
		if (obj == null) {
			return null;
		}
		return serviceresuest.proxies.Enum_EquipmentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EquipmentType
	 * @param equipmenttype
	 */
	public final void setEquipmentType(serviceresuest.proxies.Enum_EquipmentType equipmenttype)
	{
		setEquipmentType(getContext(), equipmenttype);
	}

	/**
	 * Set value of EquipmentType
	 * @param context
	 * @param equipmenttype
	 */
	public final void setEquipmentType(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Enum_EquipmentType equipmenttype)
	{
		if (equipmenttype != null) {
			getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), equipmenttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), null);
		}
	}

	/**
	 * @return value of ManufactureDate
	 */
	public final java.util.Date getManufactureDate()
	{
		return getManufactureDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ManufactureDate
	 */
	public final java.util.Date getManufactureDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ManufactureDate.toString());
	}

	/**
	 * Set value of ManufactureDate
	 * @param manufacturedate
	 */
	public final void setManufactureDate(java.util.Date manufacturedate)
	{
		setManufactureDate(getContext(), manufacturedate);
	}

	/**
	 * Set value of ManufactureDate
	 * @param context
	 * @param manufacturedate
	 */
	public final void setManufactureDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date manufacturedate)
	{
		getMendixObject().setValue(context, MemberNames.ManufactureDate.toString(), manufacturedate);
	}

	/**
	 * @return value of PurchaseDate
	 */
	public final java.util.Date getPurchaseDate()
	{
		return getPurchaseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PurchaseDate
	 */
	public final java.util.Date getPurchaseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PurchaseDate.toString());
	}

	/**
	 * Set value of PurchaseDate
	 * @param purchasedate
	 */
	public final void setPurchaseDate(java.util.Date purchasedate)
	{
		setPurchaseDate(getContext(), purchasedate);
	}

	/**
	 * Set value of PurchaseDate
	 * @param context
	 * @param purchasedate
	 */
	public final void setPurchaseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date purchasedate)
	{
		getMendixObject().setValue(context, MemberNames.PurchaseDate.toString(), purchasedate);
	}

	/**
	 * Get value of WarrantyStatus
	 * @param warrantystatus
	 */
	public final serviceresuest.proxies.Enum_WarrantyStatus getWarrantyStatus()
	{
		return getWarrantyStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of WarrantyStatus
	 */
	public final serviceresuest.proxies.Enum_WarrantyStatus getWarrantyStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WarrantyStatus.toString());
		if (obj == null) {
			return null;
		}
		return serviceresuest.proxies.Enum_WarrantyStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WarrantyStatus
	 * @param warrantystatus
	 */
	public final void setWarrantyStatus(serviceresuest.proxies.Enum_WarrantyStatus warrantystatus)
	{
		setWarrantyStatus(getContext(), warrantystatus);
	}

	/**
	 * Set value of WarrantyStatus
	 * @param context
	 * @param warrantystatus
	 */
	public final void setWarrantyStatus(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Enum_WarrantyStatus warrantystatus)
	{
		if (warrantystatus != null) {
			getMendixObject().setValue(context, MemberNames.WarrantyStatus.toString(), warrantystatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.WarrantyStatus.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_Equipment
	 */
	public final serviceresuest.proxies.ServiceRequest getServiceRequest_Equipment() throws com.mendix.core.CoreException
	{
		return getServiceRequest_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final serviceresuest.proxies.ServiceRequest getServiceRequest_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceresuest.proxies.ServiceRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_Equipment.toString());
		if (identifier != null) {
			result = serviceresuest.proxies.ServiceRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_Equipment
	 * @param servicerequest_equipment
	 */
	public final void setServiceRequest_Equipment(serviceresuest.proxies.ServiceRequest servicerequest_equipment)
	{
		setServiceRequest_Equipment(getContext(), servicerequest_equipment);
	}

	/**
	 * Set value of ServiceRequest_Equipment
	 * @param context
	 * @param servicerequest_equipment
	 */
	public final void setServiceRequest_Equipment(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.ServiceRequest servicerequest_equipment)
	{
		if (servicerequest_equipment == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Equipment.toString(), servicerequest_equipment.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final serviceresuest.proxies.Equipment that = (serviceresuest.proxies.Equipment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
