// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package serviceresuest.proxies;

public class ServiceRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceResuest.ServiceRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceRequestID("ServiceRequestID"),
		ServiceType("ServiceType"),
		Status("Status"),
		Description("Description"),
		CompletionDate("CompletionDate"),
		TechnicianRemarks("TechnicianRemarks"),
		ServiceRequest_Equipment("ServiceResuest.ServiceRequest_Equipment"),
		ServiceRequest_WorkOrder("ServiceResuest.ServiceRequest_WorkOrder"),
		Document_ServiceRequest("ServiceResuest.Document_ServiceRequest"),
		ServiceRequest_Customer("ServiceResuest.ServiceRequest_Customer"),
		ServiceRequest_Account_AssignedTechnician("ServiceResuest.ServiceRequest_Account_AssignedTechnician");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceRequestMendixObject)
	{
		if (serviceRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, serviceRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.serviceRequestMendixObject = serviceRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static serviceresuest.proxies.ServiceRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new serviceresuest.proxies.ServiceRequest(context, mendixObject);
	}

	public static serviceresuest.proxies.ServiceRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return serviceresuest.proxies.ServiceRequest.initialize(context, mendixObject);
	}

	public static java.util.List<serviceresuest.proxies.ServiceRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> serviceresuest.proxies.ServiceRequest.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ServiceRequestID
	 */
	public final java.lang.Long getServiceRequestID()
	{
		return getServiceRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequestID
	 */
	public final java.lang.Long getServiceRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ServiceRequestID.toString());
	}

	/**
	 * Set value of ServiceRequestID
	 * @param servicerequestid
	 */
	public final void setServiceRequestID(java.lang.Long servicerequestid)
	{
		setServiceRequestID(getContext(), servicerequestid);
	}

	/**
	 * Set value of ServiceRequestID
	 * @param context
	 * @param servicerequestid
	 */
	public final void setServiceRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long servicerequestid)
	{
		getMendixObject().setValue(context, MemberNames.ServiceRequestID.toString(), servicerequestid);
	}

	/**
	 * Get value of ServiceType
	 * @param servicetype
	 */
	public final serviceresuest.proxies.Enum_Type getServiceType()
	{
		return getServiceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceType
	 */
	public final serviceresuest.proxies.Enum_Type getServiceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ServiceType.toString());
		if (obj == null) {
			return null;
		}
		return serviceresuest.proxies.Enum_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ServiceType
	 * @param servicetype
	 */
	public final void setServiceType(serviceresuest.proxies.Enum_Type servicetype)
	{
		setServiceType(getContext(), servicetype);
	}

	/**
	 * Set value of ServiceType
	 * @param context
	 * @param servicetype
	 */
	public final void setServiceType(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Enum_Type servicetype)
	{
		if (servicetype != null) {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), servicetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), null);
		}
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final serviceresuest.proxies.Enum_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final serviceresuest.proxies.Enum_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return serviceresuest.proxies.Enum_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(serviceresuest.proxies.Enum_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Enum_Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate()
	{
		return getCompletionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionDate
	 */
	public final java.util.Date getCompletionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletionDate.toString());
	}

	/**
	 * Set value of CompletionDate
	 * @param completiondate
	 */
	public final void setCompletionDate(java.util.Date completiondate)
	{
		setCompletionDate(getContext(), completiondate);
	}

	/**
	 * Set value of CompletionDate
	 * @param context
	 * @param completiondate
	 */
	public final void setCompletionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completiondate)
	{
		getMendixObject().setValue(context, MemberNames.CompletionDate.toString(), completiondate);
	}

	/**
	 * @return value of TechnicianRemarks
	 */
	public final java.lang.String getTechnicianRemarks()
	{
		return getTechnicianRemarks(getContext());
	}

	/**
	 * @param context
	 * @return value of TechnicianRemarks
	 */
	public final java.lang.String getTechnicianRemarks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TechnicianRemarks.toString());
	}

	/**
	 * Set value of TechnicianRemarks
	 * @param technicianremarks
	 */
	public final void setTechnicianRemarks(java.lang.String technicianremarks)
	{
		setTechnicianRemarks(getContext(), technicianremarks);
	}

	/**
	 * Set value of TechnicianRemarks
	 * @param context
	 * @param technicianremarks
	 */
	public final void setTechnicianRemarks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String technicianremarks)
	{
		getMendixObject().setValue(context, MemberNames.TechnicianRemarks.toString(), technicianremarks);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_Equipment
	 */
	public final serviceresuest.proxies.Equipment getServiceRequest_Equipment() throws com.mendix.core.CoreException
	{
		return getServiceRequest_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final serviceresuest.proxies.Equipment getServiceRequest_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceresuest.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_Equipment.toString());
		if (identifier != null) {
			result = serviceresuest.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_Equipment
	 * @param servicerequest_equipment
	 */
	public final void setServiceRequest_Equipment(serviceresuest.proxies.Equipment servicerequest_equipment)
	{
		setServiceRequest_Equipment(getContext(), servicerequest_equipment);
	}

	/**
	 * Set value of ServiceRequest_Equipment
	 * @param context
	 * @param servicerequest_equipment
	 */
	public final void setServiceRequest_Equipment(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Equipment servicerequest_equipment)
	{
		if (servicerequest_equipment == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Equipment.toString(), servicerequest_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_WorkOrder
	 */
	public final serviceresuest.proxies.WorkOrder getServiceRequest_WorkOrder() throws com.mendix.core.CoreException
	{
		return getServiceRequest_WorkOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_WorkOrder
	 * @throws com.mendix.core.CoreException
	 */
	public final serviceresuest.proxies.WorkOrder getServiceRequest_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceresuest.proxies.WorkOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_WorkOrder.toString());
		if (identifier != null) {
			result = serviceresuest.proxies.WorkOrder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_WorkOrder
	 * @param servicerequest_workorder
	 */
	public final void setServiceRequest_WorkOrder(serviceresuest.proxies.WorkOrder servicerequest_workorder)
	{
		setServiceRequest_WorkOrder(getContext(), servicerequest_workorder);
	}

	/**
	 * Set value of ServiceRequest_WorkOrder
	 * @param context
	 * @param servicerequest_workorder
	 */
	public final void setServiceRequest_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.WorkOrder servicerequest_workorder)
	{
		if (servicerequest_workorder == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_WorkOrder.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_WorkOrder.toString(), servicerequest_workorder.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Document_ServiceRequest
	 */
	public final serviceresuest.proxies.Document getDocument_ServiceRequest() throws com.mendix.core.CoreException
	{
		return getDocument_ServiceRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of Document_ServiceRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final serviceresuest.proxies.Document getDocument_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceresuest.proxies.Document result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Document_ServiceRequest.toString());
		if (identifier != null) {
			result = serviceresuest.proxies.Document.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Document_ServiceRequest
	 * @param document_servicerequest
	 */
	public final void setDocument_ServiceRequest(serviceresuest.proxies.Document document_servicerequest)
	{
		setDocument_ServiceRequest(getContext(), document_servicerequest);
	}

	/**
	 * Set value of Document_ServiceRequest
	 * @param context
	 * @param document_servicerequest
	 */
	public final void setDocument_ServiceRequest(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.Document document_servicerequest)
	{
		if (document_servicerequest == null) {
			getMendixObject().setValue(context, MemberNames.Document_ServiceRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Document_ServiceRequest.toString(), document_servicerequest.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_Customer
	 */
	public final useraccount.proxies.Customer getServiceRequest_Customer() throws com.mendix.core.CoreException
	{
		return getServiceRequest_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final useraccount.proxies.Customer getServiceRequest_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		useraccount.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_Customer.toString());
		if (identifier != null) {
			result = useraccount.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_Customer
	 * @param servicerequest_customer
	 */
	public final void setServiceRequest_Customer(useraccount.proxies.Customer servicerequest_customer)
	{
		setServiceRequest_Customer(getContext(), servicerequest_customer);
	}

	/**
	 * Set value of ServiceRequest_Customer
	 * @param context
	 * @param servicerequest_customer
	 */
	public final void setServiceRequest_Customer(com.mendix.systemwideinterfaces.core.IContext context, useraccount.proxies.Customer servicerequest_customer)
	{
		if (servicerequest_customer == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Customer.toString(), servicerequest_customer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_Account_AssignedTechnician
	 */
	public final administration.proxies.Account getServiceRequest_Account_AssignedTechnician() throws com.mendix.core.CoreException
	{
		return getServiceRequest_Account_AssignedTechnician(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_Account_AssignedTechnician
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getServiceRequest_Account_AssignedTechnician(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_Account_AssignedTechnician.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_Account_AssignedTechnician
	 * @param servicerequest_account_assignedtechnician
	 */
	public final void setServiceRequest_Account_AssignedTechnician(administration.proxies.Account servicerequest_account_assignedtechnician)
	{
		setServiceRequest_Account_AssignedTechnician(getContext(), servicerequest_account_assignedtechnician);
	}

	/**
	 * Set value of ServiceRequest_Account_AssignedTechnician
	 * @param context
	 * @param servicerequest_account_assignedtechnician
	 */
	public final void setServiceRequest_Account_AssignedTechnician(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account servicerequest_account_assignedtechnician)
	{
		if (servicerequest_account_assignedtechnician == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Account_AssignedTechnician.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_Account_AssignedTechnician.toString(), servicerequest_account_assignedtechnician.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serviceRequestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final serviceresuest.proxies.ServiceRequest that = (serviceresuest.proxies.ServiceRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
