// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package serviceresuest.proxies;

public class WorkOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ServiceResuest.WorkOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkOrderID("WorkOrderID"),
		WorkOrderNumber("WorkOrderNumber"),
		LineItem("LineItem"),
		ServiceCost("ServiceCost"),
		ServiceRequest_WorkOrder("ServiceResuest.ServiceRequest_WorkOrder"),
		WorkOrder_Customer("ServiceResuest.WorkOrder_Customer");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderMendixObject)
	{
		if (workOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderMendixObject = workOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static serviceresuest.proxies.WorkOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new serviceresuest.proxies.WorkOrder(context, mendixObject);
	}

	public static serviceresuest.proxies.WorkOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return serviceresuest.proxies.WorkOrder.initialize(context, mendixObject);
	}

	public static java.util.List<serviceresuest.proxies.WorkOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> serviceresuest.proxies.WorkOrder.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of WorkOrderID
	 */
	public final java.lang.Long getWorkOrderID()
	{
		return getWorkOrderID(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderID
	 */
	public final java.lang.Long getWorkOrderID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.WorkOrderID.toString());
	}

	/**
	 * Set value of WorkOrderID
	 * @param workorderid
	 */
	public final void setWorkOrderID(java.lang.Long workorderid)
	{
		setWorkOrderID(getContext(), workorderid);
	}

	/**
	 * Set value of WorkOrderID
	 * @param context
	 * @param workorderid
	 */
	public final void setWorkOrderID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long workorderid)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderID.toString(), workorderid);
	}

	/**
	 * @return value of WorkOrderNumber
	 */
	public final java.lang.String getWorkOrderNumber()
	{
		return getWorkOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderNumber
	 */
	public final java.lang.String getWorkOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderNumber.toString());
	}

	/**
	 * Set value of WorkOrderNumber
	 * @param workordernumber
	 */
	public final void setWorkOrderNumber(java.lang.String workordernumber)
	{
		setWorkOrderNumber(getContext(), workordernumber);
	}

	/**
	 * Set value of WorkOrderNumber
	 * @param context
	 * @param workordernumber
	 */
	public final void setWorkOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workordernumber)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderNumber.toString(), workordernumber);
	}

	/**
	 * @return value of LineItem
	 */
	public final java.lang.String getLineItem()
	{
		return getLineItem(getContext());
	}

	/**
	 * @param context
	 * @return value of LineItem
	 */
	public final java.lang.String getLineItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LineItem.toString());
	}

	/**
	 * Set value of LineItem
	 * @param lineitem
	 */
	public final void setLineItem(java.lang.String lineitem)
	{
		setLineItem(getContext(), lineitem);
	}

	/**
	 * Set value of LineItem
	 * @param context
	 * @param lineitem
	 */
	public final void setLineItem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lineitem)
	{
		getMendixObject().setValue(context, MemberNames.LineItem.toString(), lineitem);
	}

	/**
	 * @return value of ServiceCost
	 */
	public final java.math.BigDecimal getServiceCost()
	{
		return getServiceCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceCost
	 */
	public final java.math.BigDecimal getServiceCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ServiceCost.toString());
	}

	/**
	 * Set value of ServiceCost
	 * @param servicecost
	 */
	public final void setServiceCost(java.math.BigDecimal servicecost)
	{
		setServiceCost(getContext(), servicecost);
	}

	/**
	 * Set value of ServiceCost
	 * @param context
	 * @param servicecost
	 */
	public final void setServiceCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal servicecost)
	{
		getMendixObject().setValue(context, MemberNames.ServiceCost.toString(), servicecost);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ServiceRequest_WorkOrder
	 */
	public final serviceresuest.proxies.ServiceRequest getServiceRequest_WorkOrder() throws com.mendix.core.CoreException
	{
		return getServiceRequest_WorkOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceRequest_WorkOrder
	 * @throws com.mendix.core.CoreException
	 */
	public final serviceresuest.proxies.ServiceRequest getServiceRequest_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		serviceresuest.proxies.ServiceRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ServiceRequest_WorkOrder.toString());
		if (identifier != null) {
			result = serviceresuest.proxies.ServiceRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ServiceRequest_WorkOrder
	 * @param servicerequest_workorder
	 */
	public final void setServiceRequest_WorkOrder(serviceresuest.proxies.ServiceRequest servicerequest_workorder)
	{
		setServiceRequest_WorkOrder(getContext(), servicerequest_workorder);
	}

	/**
	 * Set value of ServiceRequest_WorkOrder
	 * @param context
	 * @param servicerequest_workorder
	 */
	public final void setServiceRequest_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, serviceresuest.proxies.ServiceRequest servicerequest_workorder)
	{
		if (servicerequest_workorder == null) {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_WorkOrder.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceRequest_WorkOrder.toString(), servicerequest_workorder.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrder_Customer
	 */
	public final useraccount.proxies.Customer getWorkOrder_Customer() throws com.mendix.core.CoreException
	{
		return getWorkOrder_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrder_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final useraccount.proxies.Customer getWorkOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		useraccount.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrder_Customer.toString());
		if (identifier != null) {
			result = useraccount.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrder_Customer
	 * @param workorder_customer
	 */
	public final void setWorkOrder_Customer(useraccount.proxies.Customer workorder_customer)
	{
		setWorkOrder_Customer(getContext(), workorder_customer);
	}

	/**
	 * Set value of WorkOrder_Customer
	 * @param context
	 * @param workorder_customer
	 */
	public final void setWorkOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context, useraccount.proxies.Customer workorder_customer)
	{
		if (workorder_customer == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Customer.toString(), workorder_customer.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final serviceresuest.proxies.WorkOrder that = (serviceresuest.proxies.WorkOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
